M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Wed 02 Aug 2023 12:12:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-02T12:12:07+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2165
%
G90
G05
T1
X7.6378Y-5.9055
X8.1102Y-5.9055
T2
X7.874Y-5.9055
T0
M30
