M48
; DRILL file {KiCad 7.0.2} date Wed Sep 13 12:46:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-13T12:46:11+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X194.0Y-150.0
X206.0Y-150.0
T2
X200.0Y-150.0
T0
M30
